GradientBoostingClassifier:
  classpath: sklearn.ensemble.GradientBoostingClassifier
  optimization_objective: f1_score
  search_space:
    n_estimators:
      type: int
      range: [50, 500]
      log: false
    learning_rate:
      type: float
      range: [0.01, 0.5]
      log: true
    max_depth:
      type: int
      range: [3, 15]
      log: false
    min_samples_split:
      type: int
      range: [2, 20]
      log: false
    min_samples_leaf:
      type: int
      range: [1, 20]
      log: false
    subsample:
      type: float
      range: [0.5, 1.0]
      log: false
    max_features:
      type: float
      range: [0.1, 1.0]
      log: false
  default_params:
    random_state: 42
