FairLearn:
  classpath: fairlearn.reductions.ExponentiatedGradient
  base_estimator:
    classpath: sklearn.linear_model.LogisticRegression
    kwargs:
      C:
        type: float
        range: [0.001, 100]
        log: True
      max_iter:
        type: int
        range: [100, 1000]
        log: False
      random_state: 42
  constraint_type: "DemographicParity"
  kwargs:
    eps:
      type: float
      range: [0.01, 0.5]
      log: False
    nu:
      type: float
      range: [0.01, 0.5]
      log: False
    eta0:
      type: float
      range: [0.1, 10.0]
      log: True
    max_iter:
      type: int
      range: [10, 100]
      log: False